# Generated by Django 3.0.5 on 2020-06-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorsPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('date_Created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Editors_pick')),
            ],
        ),
    ]
