# Generated by Django 3.0.5 on 2020-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_editorspick_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(max_length=50)),
                ('date_Created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Trends')),
            ],
        ),
    ]
