# Generated by Django 3.0.5 on 2020-06-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_trending_mainpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='mainpost',
        ),
    ]
