# Generated by Django 3.0.5 on 2020-06-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_innovation_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Innovation',
            new_name='Posts',
        ),
        migrations.DeleteModel(
            name='Programming',
        ),
    ]
