# Generated by Django 3.0.5 on 2020-06-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_commentstrending'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentstrending',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
