# Generated by Django 3.0.5 on 2020-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_commentstrending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstrending',
            name='comment',
            field=models.TextField(),
        ),
    ]
